- __init__.py
- artnet.py
- data.py
Hi!
I wanted to share my branch, perhaps some or all of the code can be merged.
This was basically my attempt to fix all errors: segmentation faults and other errors that came up in Blender console.
1. First I moved the `dmx.render` method out of the thread and into a Timer (see lines [95](https://github.com/hugoaboud/blenderDMX/compare/main...kasparsj:blenderDMX:kasparsj-segfault-1?expand=1#diff-55facb600782a28602668c1d337b786089197b5ef483116337ad153b5f5dce75R93), [111](https://github.com/hugoaboud/blenderDMX/compare/main...kasparsj:blenderDMX:kasparsj-segfault-1?expand=1#diff-55facb600782a28602668c1d337b786089197b5ef483116337ad153b5f5dce75R112)), this made huge difference - no segfaults while running the scene
2. I was running Blender 3.2.1 and when I quit running a DMX scene, it would …
> Fixing segfaults and other issues

- gdtf.py
- pygdtf/__init__.py
This allows loading glTF (glbs are [specified](https://github.com/mvrdevelopment/spec/blob/main/gdtf-spec.md#regarding-gltf-files)) based models.
Also, it fixes a crash when loading DMX Macros.
> Load glb models

- .gitignore
- __init__.py
- fixture.py
- gdtf.py
- panels/programmer.py
- panels/setup.py
- pygdtf/__init__.py
- util.py
This adds several things:
* initial Zoom support
* initial ColorSub_C/M/Y support
* fixed the ColorAdd_R/G/B attribute support (not sure how this worked before... perhaps the original devices used R, G, B instead of the GDTF attributes...?)
* added Pigtail settings - this is not updated in realtime but only during adding/editing of a device
* catch several crash errors
Please let me know if i miss some of the formats or variable camelCasing.
> Adding Zoom and ColorSub_C/M/Y GDTF attributes, Pigtail settings, catch several crash errors

- material.py
- panels/setup.py
There were a few issues with the `v1.0.0` `Volume Box` feature.
- When creating the material, it was trying to delete the "Principled BSDF" node twice.
- The object was wrongly linked to the scene collection, when it should remain inside the "DMX" collection, which caused errors on Update.
> Volume Box fails on create and update

- panels/setup.py
This fixes the error some people are having with the material not existing.
> Handle empty volume.data.materials

- __init__.py
- fixture.py
- pymvr/__init__.py
This updates pymvr, which now supports parsing of focus in fixtures and FocusPoints in scene. During import to BlenderDMX, this data is used to set the Target.
> Add support for focus points during MVR import

- __init__.py
- fixture.py
- only extract GDTF from MVR once for each device type
- stop the renderer while importing from MVR
The above helped to gain a bit of speed and prevent some Blender segfaults. This code is already formatted by black.
> MVR Import optimizations:

- __init__.py
- fixture.py
- gdtf.py
- mvr.py
- panels/fixtures.py
- panels/setup.py
- move and rename the "mvr in progress" bool to a temporary object and rename it to "render pause", to better indicate it's meaning
- use the pausing of renderer during 2D view and also during GDTF fixture edits (to prevent render issue during partially imported state)
- use hashing for collection names as there seems to be a limit to collection names - this speeds up GDTF loading
- use caching during MVR import by creating a caching collection. 2x speed up achieved during import
- handle glb files composed of multiple models
- update switching to 2D to support Blender 4.x
> Improve MVR import speed by 2x

- __init__.py
- fixture.py
- gdtf.py
- mvr.py
- panels/dmx.py
- panels/fixtures.py
- panels/programmer.py
- add Fixture ID and other related MVR fields to Fixture. This is essential for the future when re-loading MVR files.
- allow quick grouping of selected targets, to point devices to one location
- improve models loading, to support another 3 specific fixture manufacturers' models specifics
- handle situation if World is missing in user workspace
- remove fixture from groups when removing fixture
- display fixture revision in fixture list of patching menu
-  Add Fixture ID... as columns in Fixture list, allow select visible columns
> Fixture id properties

- __init__.py
- group.py
- mvr.py
- panels/fixtures.py
When renaming fixtures, groups would be no longer working. This fixes it and improves the handling of UUIDs.
> Improve groups

- __init__.py
- fixture.py
- panels/fixtures.py
- panels/groups.py
- allow changing fixture selection with Ctrl-Left, Ctrl-Right keyabord shortcuts
- add possibility to remove fixture added in a faulty state
- show number of devices in a group
- improve the "Re-address only" dialog to only show fields which will be used
> Fixture selection previous/next by keyboard

- __init__.py
- data.py
Add custom namespace driver for Blender, to use DMX for general animations.
One can add: `#bdmxc(1,1)` to any field in Blender to receive first address of first universe as a value for this field.
The syntax is #bdmxX(universe, address), where X is c or f (coarse, fine)
> Custom BlenderDMX namespace driver

- __init__.py
- artnet.py
- data.py
- fixture.py
- panels/dmx.py
- panels/fixtures.py
- universe.py
- rename default universe name from "DMX" to "Universe"
- allow to enable Art-Net/sACN only if at least one universe is set to these sources. 
- allow to choose a Live DMX view only to universes which are preset, rather then an arbitrary protocol/universe combination
- ensure universe exists also when editing fixture universe in the new fixture view
> Make setting universes more understandable

- __init__.py
- fixture.py
- gdtf.py
- material.py
- panels/fixtures.py
- panels/programmer.py
- panels/setup.py
- initial support for gobos
- loads gobo images from GDTF
- gobo selection, indexing and rotation
- crashes Blender 3.6 in Cycles but works correctly in Blender 4.x
[gobo_wip.webm](https://github.com/open-stage/blender-dmx/assets/3680926/eafb2495-97a4-4793-9f09-82be2bd81243)
> WIP: Initial gobo support

- .pre-commit-config.yaml
- DEVELOPMENT.md
- scripts/check-prints.py
Not enabled on the repo by default, can be run with pre-commit. 
- Checks for and fixes trailing white space
- Checks for large files being added
- Checks for debug statements
- Checks for print statements, except those with first argument "INFO", which are useful on startup, linking file and MVR import
> Add pre-commit hook configuration

- __init__.py
- fixture.py
- gdtf.py
- panels/recorder.py
- Add support to keyframe gobos
- Handle hiding of gobo geometry
- Loading of gobos had to be redone to load images as Blender image sequence. Previous blender files can be updated by editing GDTF fixtures - reloading the GDTF files
> Support gobo keyframing

- fixture.py
- mvr.py
- panels/recorder.py
- add support for Gobos in Cycles, including rotation and setting to clean beam when gobo == 0
- ensure keyframing works
- ensure delete keyframes removes deeper node_tree animations in lights
- handle possible missing file in MVR import
> Add support for Gobos in Cycles

- CHANGELOG.md
- README.md
- __init__.py
- fixture.py
- gdtf.py
* Add support for gobos in Cycles
* Add translation of UI
* Add Noise Scatter to Volume box
* Enable programmer only if any fixture is selected
* Small improvements:
* GDTF download: Better sanitizing of GDTF download file name
* Handle ArtNet status setting error
* MVR import: check if file exists before loading it
* Handle fixtures without dimmer
* Handle fixtures with gobo but without zoom
> Release v1.3.0

- CHANGELOG.md
- README.md
- __init__.py
* Add support to import IES photometrics and apply them to beams in Cycles
* Allow changing beam lens diameter for Cycles, based on global or per fixture settings
* Set hidden objects as hidden also for renderer
* Make more items translatable, disable automatic translation for Fixture controls
* Add version checks on start for Python, Blender, and for the BlenderDMX addon
> Release 1.3.1

- __init__.py
- fixture.py
- panels/fixtures.py
- panels/programmer.py
- Provide shortcut to select prev/next Target (Ctrl-Shift-Left/Right)
- Ensure that keyframes are saved when programming position by Target
- Set Ignore pan/tilt DMX (lock target) after using Target to set position, to allow programming keyframes by Target
- Indicate pan/tilt lock and provide quick unlock in programmer
- Support multiple pan/tilt geometries for fixtures without Target
> Improvements to pan/tilt handling

- fixture.py
Due to refactor of pan/tilt behavior in the render function a previously used `return` remained in now `if` condition and prematurely ended all other renders.
> Bugfix of pan/tilt lock

- pygdtf/__init__.py
- pymvr/__init__.py
Some software started exporting xml files in GDTF and MVR with an extra null byte at the end. Handle it on our side.
> Handle XML files with null byte at the end

- __init__.py
- panels/setup.py
> Display device label (name, id, or dmx) in 2D view

- CHANGELOG.md
- README.md
- RELEASE.md
- __init__.py
* Fix Intel Mac crashing on Create New Show - remove unnecessary setup
class unregistration
* Display device label (name, id, or dmx) in 2D
* Rework 'Re-address only' to 'Advanced edit' for clarity
* Add Clear Project data button to clear the addon directory
* Add development related 'Reload BlenderDMX addon' button to Extras
* Update translations
* Reload profiles after data clearing or loading
* Fix Volume box migration - prevent always deleting volume box on file
load
* Fix gobo projection for fixtures without zoom
* Fix 'Clear/Clear all' in Programmer
* Fix ColorPicker when mixing single unit
> Release 1.4.3

- fixture.py
- gdtf.py
- mvr.py
This makes many things better - object trees now have correct top-down rotations, offsets and placements.
Apply *-1 to rotations, this seems to fix several issues with assembly of complex trees.
> Rework of GDTF geometries assembly process - use parenting instead of constrains

- fixture.py
- gdtf.py
Currently, only 255 gobos or colorwheel colors are supported. Prevent errors if a fixture contains more.
> Limit number of colors/gobos to 255

- CHANGELOG.md
- README.md
- __init__.py
* Aligning release of the Addon with the Extension release
* Fix showing fixtures after disabling 2D layout view
* Adding RGB glowing tube BlenderDMX provided device
* Adding Zoom and Gobos to the BlenderDMX provided Beam GDTF file
* Add custom cutoff_distance to lights to make gobos work in Eevee Next
* Remove onDepsgraph - prevents crashes and improves performance
* Big changes in architecture of the python code
* Fix several visible and invisible issues
* Translated using Weblate (Polish) [WaldiS], (Spanish) [Josman Goncalves Bravo], (German) [Ettore Atalan]
* Loading 3DS with apply transforms enabled for better results
* Apply position of referring geometry to geometry reference
* Create gobo plane only for fixtures with gobo for better performance
* Open shutter at 0 also at 255
* …
> Release 1.5.0

- CHANGELOG.md
- README.md
- __init__.py
* Internal file reorganization, license headers, reformatting
* Make internal programmer to set values for Live DMX view
* Fixtures name autogeneration adjustments
* Add PosiStageNet (PSN) protocol with up to 10 PSN slots
* Add warning message for Blender 4.2. Add link to help to Extras
* Add Blender logo as gobo image to bundled beam
* Improve vectors of BlenderDMX logo gobo in bundled beam fixture
> Release 1.6.0

- dmx.py
- fixture.py
- logging.py
- mvr.py
- panels/setup.py
- pymvr/__init__.py
- pymvr/value.py
- util.py
Initial basic but working MVR export. Exports a single MVR layer with fixtures and their GDTFs.
> Initial MVR export for fixtures

- CHANGELOG.md
- README.md
- __init__.py
* Initial MVR export - fixtures and focus points on one layer
* Ensure fixture name is unique when importing from MVR
* Fix dimmer if only one beam geometry exists
> Release 1.7.0

- dmx.py
- io_scene_3ds/import_3ds.py
- mvr.py
Complete refactor of mvr.py including:
1. Avoid importing meshes multiple times
2. Use collection instances for symbol objects
3. Use already imported collections instead of creating new
4. Use object uuids instead of hashlib or collection names
5. Create custom properties for MVR class, name, uuid and reference
6. Fixed matrix transformations
7. Fixed names if they are doubles
8. Importing is now about 10 times faster
> Refactoring mvr.py

- in_gdtf.py
- in_out_mvr.py
This ensures that:
In/Out GDTF/MVR dialogs work in 3.4, 4.0, 4.1, 4.2.
Drag and drop works in 4.2.
Import of MVR on new startup (when DMX scene has not yet been created) now works and does not crash blender.
> Import export version checks

- mvr.py
1. Scene is now reseted correctly if same mvr imported again
2. Objects got a transform property wich saves the original transformation into a 4x3 matrix
3. The 4x3 matrix can be used to export the object again with the correct matrix
4. added code wich was previously removed
5. exchanged prints with dmx log
> mvr: Improved scene reset if mvr imported again

- gdtf.py
In some gdtf files I tested the model dimensions are equal with blender dimensions.  This commit checks the dimensions before transforming the 3ds models to vectorworks scale.
> gdtf: Check model dimensions before 3ds transform

- i18n/__init__.py
- in_out_mvr.py
- mvr.py
- panels/profiles/README.md
- panels/profiles/controller/manager.py
- panels/profiles/data/share_profile.py
- share_api_client/__init__.py
Normally, the `pre-commit` is run after `git add <files>`, before running `git commit`, but one can also call `pre-commit run --all-files` to see issues with all files in the repo. This PR replaces some prints with logging and in some deeper places, harder to test, it adds "INFO", which is exempting print from being denied.
> Eliminate some of the print statements and whitespace, to pass pre-commit hook

- gdtf.py
After testing a plenty of gdtf, I found out that the scaling of geometries can have different factors and is not always 0.001 (this is only the case if they were exported from vectorworks), some have factor 0.01 or 0.1, resulting in wrong scaling. It is better to transform the meshes after joining the meshes of a 3ds file. Then calculate the correct factor. This will result in correct scale so it is not nessecary to set the scale again, this is now only nessecary for glb files.
> gdtf: Apply transformation after joining the objects

- gdtf.py
- mvr.py
gdtf: If any fixture has multiple heads and yokes, also add another constraint for them.
Improved transformations
mvr: Deselect all objects before import because selected objects will be processed
>  gdtf: Add constraints for multiple heads and yokes

- in_gdtf.py
- scripts/get_testing_gdtfs.py
- scripts/test_fixture_patching.py
This adds the possibility to download files for testing of imports and 3d representation.
Testing script (executed via blender as a python module) can import these files, to (quickly) show possible issues. This is just an initial stab at some possible testing in the future.
> Add testing scripts/files

- gdtf.py
If the childs have any children also the root geometry attribute has to be transfered to the children
> gdtf: Transfer root geometry attribute to children

- CHANGELOG.md
- README.md
- __init__.py
- in_gdtf.py
- in_out_mvr.py
* Allow using user writable directory associated with an extension (extension only)
* Show fixture name in Align panel if it is a selected active object
* Fix count of selected fixtures in Programmer, Align, and other panels
* Ensure that the beam has full diameter at the lense in Cycles for Blender 4.1 and up
* MVR import:
* Deselect all objects before import to prevent issues
* Add support for MVR classing to show/hide MVR classes
* GDTF import:
* Add constraints for multiple heads and yokes
* Apply transformation after joining the objects
* Check dimensions with safer method
* Allow import of existing files
* Use DMX break overwrite only for Geometry References
* Transfer root geometry attribute to children for complex fixtures
* Improved creating constraints and removed pixel factor
* …
> Release v1.7.5

- CHANGELOG.md
- blender_manifest.toml
* MVR-xchange networking working also on Windows:
* Tweak networking to get port number on Windows hosts
* List only MVR-xchange clients with at least minimal required data
* Do not allow empty mDNS service group
* Add network interface selection
> Release v1.8.3

- gdtf.py
This PR changes how the 2d thumbnails are loaded into the scene.
Looking at the current implementation, and the git line history, it seems that there is no particular reason (previous bugfix, etc.) why the line provided the file name in the files array rather than just as the file path, when the array only gave one file anyway!
By loading it in the previous way, it ended up creating two objects on some systems, one called "primitives" (which is the last part of the path given to `filepath`), and one which was the thumbnail itself. It then moved `primitive` in as the 2D thumbnail, which had no data and therefore no material, causing a crash.
With thanks to b48g55m on the Discord who helped find the source of this problem.
> Fix an `IndexError` when creating fixtures on some systems

- blender_utils.py
- dmx.py
- mdns.py
- mvrx_protocol.py
- panels/setup.py
- remove old online version check
- make application uuid to be (optionally, enabled by default) per blend file
- add option (disabled by default) to add hostname to sub-sub service in mDNS
> Add per file application UUID, make hostname in mDNS service optional

- dmx.py
- fixture.py
This PR redoes the dimmer/shutter to use physical values from channel functions.
The older timer base strobe has been replaced by driver, this means the animation player must be playing for this to be shown.
Keyframing is still somewhat of an issue as Blender doesn't like to pre-calculate the light power, but one can do autokeyframing and keep moving the dimmer, to store the strobing.
This PR also adds light intensity compensation when zooming, to address this issue https://github.com/open-stage/blender-dmx/issues/7 . There is room for improvements, as always.
> Shutter/dimmer as keyframable physical values. Zoom intensity compensation.

- CHANGELOG.md
- blender_manifest.toml
* Add support for ChannelFunctions and ChannelSets with their Physical From,
Physical To and WheelSlotIndex:
* Add this support to following GDTF Attributes:
* Pan, Tilt, PanRotate, TiltRotate, Zoom
* CTC, CTB, CTO, Iris
* Shutter1, Dimmer, ShutterStrobe
* Color1, Color2, Color3, ColorMacro1
* Gobo1, Gobo1Pos, Gobo1PosRotate
* Gobo2, Gobo2Pos, Gobo2PosRotate
* Add support for Mode Masters
* Add optional BlenderDMX defined default Physical From/To values
* Reworked Shutter/Dimmer - removed complex code
* Added compensation of intensity when zooming
* Adjusted and separated color related code
* Add support for PanMode, TiltMode, and PanTiltMode GDTF Attributes
* Add support for emitter models with multiple materials
* Add option to ignore Target during programming
* Fix DMX breaks during …
> Release v2.0.0

- fixture.py
- gdtf.py
If a moving geometry has a defined offset, we need to ensure that pan/tilt include the offset
> Apply geometry offset

- fixture.py
Add per-dmx channel caching to render. Make sure mode master related channels are checked too.
> Add per-channel caching to render()

- CHANGELOG.md
- blender_manifest.toml
- pyproject.toml
* Improve migration from older blend files
* Unify programmer defaults
* Fix gobo indexing angle calculation
* Update packaged fixture profiles:
- keep only BlenderDMX created profiles
- improve the default profiles with more data
- provide RGBW/RGBA versions
- REMOVED some files like rotating beam or source4, they exist in the GDTF
Share
* Add per-channel caching to render()
* Save and apply XML provided offset to pan/tilt geometrie
* Map pan, tilt, color picker to DMX RGB/CMY correctly and without drifting
> Release v2.0.1

- CHANGELOG.md
- blender_manifest.toml
* Update pygdtf to 1.2.4
* Sync Shutter1Strobe to the programmer
* Make Shutter1Strobe flashing, not pulsing
* Ensure that DMX breaks's address/universe are overflowing 512
* Export MVR with breaks from 0, set universe 0 as 1
* Fix programmer values after clear
* Clear any selection prior to fixture edit/mvr import
* Add option to not modify Fixture_ID and Address during Edit
* Ensure that color defined close to GDTF default white is interpreted as full white
* Remove and re-copy BlenderDMX provided files when Cleaning project data
> Release v2.0.2

- dmx.py
- mdns.py
- mvrx_protocol.py
- mvrxchange/mvr_xchange_blender.py
- mvrxchange/mvrx_message.py
- mvrxchange/mvrx_tcp_client.py
- mvrxchange/mvrx_tcp_server.py
- mvrxchange/mvrx_ws_client.py
- panels/protocols/mvr.py
- panels/setup.py
Currently, the MVR-xchange in here is able to push data only to one station (and receive data from multiple stations). This PR adds initial support for multistation operation: the "Connect" now shoots the MVR_JOIN message and marks the station in the list as "subscribed", then on commit, we push the commit to all "subscribed" stations.
> WIP: MVR-xchange multistation

- CHANGELOG.md
- blender_manifest.toml
- pyproject.toml
* Translated using Weblate:
* (Chinese (Simplified Han script)) [大学没毕业]
* (Swedish) [Daniel Nylander]
* (Polish) [Franciszek Libera]
* Handle GDTFs with models with both a file (even missing) and a primitive type defined
* Update most device profiles:
* Add Shutter/Strobe
* Add thumbnail
* Adjust name of generic fixture in MVR import
* Update to pygdtf 2.0.6, update physical values parsing
> Release v2.0.7

- CHANGELOG.md
- blender_manifest.toml
- pyproject.toml
* Prevent MVR persistence during export, to eliminate duplication during export
* Update to latest pygdtf and pymvr libraries
* Improvements to Art-Net 4 compatibility, thanks to Michael Wigard
* Ensure that Programmer Clear sets the fixtures to default values
* Ensure that fixture is set to default and rendered after being added to the
scene
> Release v2.0.8

- CHANGELOG.md
- blender_manifest.toml
- pyproject.toml
- uv.lock
* MVR:
- Initial support more MVR objects during import, like VideoScreens,
Projectors, and Support
- Add some MVR import/export filter options
- Improve layers import and export, to keep original fixture layer
assignment and layer names, especially useful for round-trip cooperation
- Initial support for fixture direct parenting - direct MVR parent is now
set as a Blender parent
- Handle MVRs with empty fixture GDTF mode
- Handle some occasionally missing structures in MVR
- MVR-xchange:
- Speed up packets packing/unpacking
- Fix header unpacking to unsigned int values
- Improvements to the pymvr library, update BlenderDMX to use the latest
version 1.0.1
* Optimize rendering for incoming signals (PSN, sACN, Art-Net)
* Added more translated strings (German, French, Portuguese, Czech)
> Release v2.0.9

- CHANGELOG.md
- blender_manifest.toml
- pyproject.toml
* Skip migrations when creating a new scene, for less verbose console output
* Added Vwx logo to MVR-xchange UI
* Updated pymvr library to 1.0.4
* Improved FocusPoint import from MVR:
- import geometries attached to Focus Points
- ensure correct position
- add classing to be able to hide these geometries
* Uploaded 3DS wheel version 2.8.0
* Updated BlenderDMX@LED_PAR_64 to fix strobing
* Russian translation update (Alex Nadzharov and Yurt Page)
> Release 2.0.12
