open-stage/blender-dmx

.gitignore
README.md
__init__.py
data.py
fixture.py
gdtf.py
group.py
material.py
model.py
panels/dmx.py
panels/fixtures.py
panels/groups.py
panels/programmer.py
panels/setup.py
param.py
scripts/build_release.py
universe.py
util.py

**Version:** v1.0.0
**Name:** Vanilla
This is the first major release of BlenderDMX. Special thanks for @vanous for the incredible work!
@kasparsj:
- #14
@vanous:
- #16
- #18
- #21
- #22
- #23
*bugfix*&ensp; 🪲 Render method moved to a Timer, to avoid segfaults (#14)
*bugfix*&ensp; 🪲 Avoid running atexit handler (#14)
*bugfix*&ensp; 🪲 Improved error handling (#14)
*feature* 🪄 Load glTF models (#16)
*bugfix*&ensp; 🪲 Fix crash when loading DMX Macros (#16)
*feature* 🪄 Initial Zoom support (#18)
*feature* 🪄 Initial ColorSub_C/M/Y support (#18)
*bugfix*&ensp; 🪲 Fix ColorAdd_R/G/B support (#18)
*feature* 🪄 Pigtail settings (#18)
*bugfix*&ensp; 🪲 Improved error handling (#18)
*improv* 🔨Improved pygdtf library (#21, #22)
*feature* 🪄 Show DMX channel count in list of DMX Modes (#21)
*feature* 🪄 …

v1.0.0 "Vanilla"

---

__init__.py

Currently it's pretty time-consuming to test changes to the code, given the two-stage registering.
This PR fixes issues which would happen when reloading the plugin.
I recommend installing [this addon](https://github.com/hextantstudios/hextant_reload_addon), so you're able to hot reload any changes to any file with `Ctrl + Alt + R`.

Add hot-reload support

---

fixture.py
gdtf.py
util.py

Merging in previous work which enables to load deeply nested geometry references, to keep the main branch up to date with latest improvements at the 1.x version.

Process deeper GeometryReference trees

---

__init__.py
acn.py
data.py

Fix a couple of issues that stopped me using the plugin:
- sACN messages with a dmxStartCode should be ignored
- Live DMX display gets stuck
Also tweak a couple of logging levels and wording.

Fix initial stumbling blocks

---

.gitignore
__init__.py
pygdtf/__init__.py
pygdtf/utils/__init__.py
pygdtf/value.py

- update pygdtf
- re-enable camera selection
- add lib to ignore

Pygdtf Updates and small fixes

---

data.py
fixture.py
gdtf.py
pymvr/__init__.py
pymvr/value.py

- update pymvr to latest version
- handle some cases from hand edited and thus not valid MVR files

Improve MVR import

---

__init__.py
fixture.py
pymvr/__init__.py
pymvr/value.py
util.py

- Apply color to fixture from MVR.
- Provide xyY to RGB and RGBA conversion functions
- Fix gel color for simple fixtures, this was a regression but unnoticed

Apply color to fixture during MVR import

---

__init__.py
mvr.py
pymvr/__init__.py

- Initial implementation
- Layers, groups, management... should still be added.
- Tested with VW and gMA3 files
- Did not check 3ds, do not have such MVR

Import other MVR based objects - scene objects, trusses

---

mvr.py

Make collections for Trusses and Scene objects when importing from MVR

MVR Import: create Truss and Scene objects collections

---

README.md

- update description for the installation procedure

Update description for the installation procedure

---

material.py

Fix issue with localized structures by requesting localized version of a string

---

mvr.py
pymvr/__init__.py
pymvr/value.py

Improve MVR parsing of GroupObjects

MVR GroupObject list

---

__init__.py
fixture.py
gdtf.py
panels/setup.py

Add initial support for 2D symbols and 2D TOP planning view

---

DEPENDENCIES.md
__init__.py
acn.py
data.py
ifaddr/__init__.py
ifaddr/_posix.py
ifaddr/_shared.py
ifaddr/_win32.py
network.py
panels/dmx.py
scripts/build_release.py

Network improvements:
- the list of IP addresses is now dynamic, taken from the computer - using [ifaddr python library](https://github.com/pydron/ifaddr) for that
- unused networking panel removed

Networking improvements

---

DEPENDENCIES.md
__init__.py
assets/osc_templates/default.json
fixture.py
osc.py
osc_utils.py
oscpy/__init__.py
oscpy/cli.py
oscpy/client.py
oscpy/parser.py
oscpy/server.py
oscpy/stats.py
panels/dmx.py
panels/fixtures.py
panels/programmer.py
scripts/build_release.py

- This allows communication between the visualizer and a DMX desk... when selecting a fixture in BlenderDMX, same fixture can be selected in a console. Clear button also clears on the console. Mapping is dynamic, via json file in the assets folder. Currently, [BlinderKitten](http://blinderkitten.lighting/) has been used and tested.
- Small rendering loop improvement has been added to skip the render if DMX for the fixture did not change. This eliminates a lot of the beam flicker when DMX is static.
- Allow fixtures list to be sorted.
- Add incrementing of FixtureID on edit

Adding OpenSoundControl support

---

.github/workflows/build-blender-addon.yaml

GH action to build addon artifact zip file

Add GH action

---

__init__.py
gdtf.py
pygdtf/value.py

Create hard/soft/none style of beam based on definition in GDTF

Honor Spot/Wash/None beam types

---

__init__.py
group.py
mvr.py
mvr_objects.py
panels/fixtures.py
pymvr/__init__.py
pymvr/value.py

This allows re-importing MVR data. Existing fixtures and objects will be updated from MVR.

Allow MVR reimport

---

__init__.py
fixture.py
model.py
mvr.py
panels/fixtures.py
pygdtf/utils/__init__.py
util.py

A bunch of improvements and fixes:
- when changing a fixture profile, apply correct geometry offsets
- preserve UUID during fixture edit/replacement
- handle errors during adding a fixture better

Editing improvements

---

CHANGELOG.md
README.md
__init__.py

Release v1.0.5

---

CHANGELOG.md
DEPENDENCIES.md
DEVELOPMENT.md
README.md
__init__.py
mdns.py
scripts/build_release.py

- MVR-xchange protocol
- ArtPollReply

Release v1.0.6

---

__init__.py
fixture.py
panels/fixtures.py
panels/programmer.py

- fixtures list is now based on the Blender's UI List which is better:
- support for filtering
- support for editable fields
- support for scrolling and setting height of the list
- all previously supported features implemented (sorting, selection, selection movement with keyboard shortcuts)
Listing mode:
Edit mode:

Rewrite of Fixture UI List

---

CHANGELOG.md
README.md
__init__.py
fixture.py
gdtf.py
panels/fixtures.py

Initial GOBO support plus other improvements and fixes

Release v1.0.8

---

CHANGELOG.md
README.md
__init__.py
acn.py
fixture.py
mvr.py
mvr_xchange.py
mvrx_protocol.py
mvrxchange/mvr_message.py
mvrxchange/mvrxchange_client/__init__.py
mvrxchange/mvrxchange_server/__init__.py
panels/dmx.py
panels/profiles/data/share_profile.py

Release v1.1.0

---

__init__.py
fixture.py
model.py
panels/fixtures.py
util.py

There could still be possible issues with different sorting due to difference in sort by UIList helper functions and normal lambda.

Select multiple fixtures in Fixture list with Shift

---

__init__.py
fixture.py
panels/recorder.py

- Supports pan, tilt, zoom, dimmer, color, emitter, XYZ_pos/rot.
- Currently not supported: gobo
- Manual and Autokeyframing
- Works from the simple programmer and from networked DMX

Add keyframe recorder

---

__init__.py
artnet.py
fixture.py
material.py
panels/programmer.py
panels/setup.py

- add migration for older blend files
- enable programmer only if any fixture is selected
- handle ArtNet status setting error

Add Noise Scatter to Volume box

---

__init__.py
i18n/messages.pot
i18n/translations/ar_AA/LC_MESSAGES/messages.po
i18n/translations/cs_CZ/LC_MESSAGES/messages.po
i18n/translations/de_DE/LC_MESSAGES/messages.po
i18n/translations/en_US/LC_MESSAGES/messages.po
i18n/translations/fr_FR/LC_MESSAGES/messages.po
i18n/translations/it_IT/LC_MESSAGES/messages.po
i18n/translations/kk_KZ/LC_MESSAGES/messages.po
i18n/translations/nb_NO/LC_MESSAGES/messages.po
i18n/translations/pl_PL/LC_MESSAGES/messages.po
i18n/translations/pt_BR/LC_MESSAGES/messages.po
i18n/translations/sv_SE/LC_MESSAGES/messages.po
i18n/translations/tr_TR/LC_MESSAGES/messages.po
i18n/translations/zh_Hans/LC_MESSAGES/messages.po
panels/setup.py

Add preference settings to customize beam lens rendering in Cycles on per-fixture bases.

Beam lens size preferences (cycles)

---

__init__.py
fixture.py
gdtf.py
i18n/messages.pot
i18n/translations/ar_AA/LC_MESSAGES/messages.po
i18n/translations/cs_CZ/LC_MESSAGES/messages.po
i18n/translations/de_DE/LC_MESSAGES/messages.po
i18n/translations/en_US/LC_MESSAGES/messages.po
i18n/translations/fr_FR/LC_MESSAGES/messages.po
i18n/translations/it_IT/LC_MESSAGES/messages.po
i18n/translations/kk_KZ/LC_MESSAGES/messages.po
i18n/translations/nb_NO/LC_MESSAGES/messages.po
i18n/translations/pl_PL/LC_MESSAGES/messages.po
i18n/translations/pt_BR/LC_MESSAGES/messages.po
i18n/translations/sv_SE/LC_MESSAGES/messages.po
i18n/translations/tr_TR/LC_MESSAGES/messages.po
i18n/translations/zh_Hans/LC_MESSAGES/messages.po
panels/fixtures.py
panels/setup.py

As per commits... quick summary here:
- Indicate IES by an icon in fixture's name
- Add Rotation to the list of editable fixture's columns
- Handle some errors
- Improve logging and add links to documentation

Improve logging and fixtures information

---

CHANGELOG.md
README.md
__init__.py
panels/fixtures.py
panels/setup.py

* Improve pan/tilt controlling and animating:
* Support multiple pan/tilt geometries for fixtures without Target
* Set Ignore pan/tilt DMX (lock target) after using Target to set
position, to allow programming keyframes by Target
* Indicate pan/tilt lock and provide quick unlock in programmer
* Ensure that keyframes are saved when programming position by Target
* Provide shortcut to select prev/next Target (Ctrl-Shift-Left/Right)
* Improve logging during addon initialization
* Fix fixture addressing procedure
* Add minimal required Blender version message to Setup panel
* Add links to documentation
* Add Rotation to the list of editable fixture's columns
* Indicate IES by an icon in fixture's name

Release v1.3.2

---

__init__.py
fixture.py

ColorRGB_Red, ColorRGB_Green, ColorRGB_Blue

Add support for ColorRGB_Red/Green/Blue color attributes

---

CHANGELOG.md
README.md
__init__.py

* Add support for ColorRGB_Red/Green/Blue color attributes
* Bug fix pan/tilt lock

Release bugfix v1.3.3

---

CHANGELOG.md
README.md
__init__.py

*  Add initial support for laser projection
*  Add Import of GDTF and MVR to Setup panel
*  Set materials for models of default fixture files
*  Add gMA3 icon to MVR-exchange stations list

Release v1.4.0

---

CHANGELOG.md
README.md
__init__.py

We need to cut a release as an important tool in the industry is now generating GDTF and MVR XML files with some extra data, which must be handled.
* Handle XML files with null byte at the end
* Add support for Color Wheels (Color1, Color2, and ColorMacro1 GDTF attributes)

Release v1.4.1

---

__init__.py
fixture.py
panels/fixtures.py
panels/programmer.py
panels/recorder.py
panels/setup.py

- only keyframe changed fixtures
- allow keyframing only selected fixtures
- indicate unsaved state in fixtures list
- fix jumping dimmer issue when resetting programmer

Keyframing improvements

---

CHANGELOG.md
README.md
__init__.py

* Provide a way to export and import custom data from/to the Addon
* Remove Blender files of old models from the Addon
* Improve keyframing:
* only keyframe fixtures with changed data
* allow keyframing only selected fixtures
* indicate unsaved state in fixtures list
* Show DMX Footprint and indicate if address is colliding in Fixtures list
* Allow fixtures deselection by groups
* Allow the Programmer data to be Applied manually when render is paused
for speedup of response on large setups
* Add icon to re-set Targets, with a selection of axis
* Italian version is now fully translated
* Ensure programmer is populated with fixture's data also when selected by
shortcuts
* Ensure that color is applied to fixtures with color wheel but without
other color mixing
* List GDTF files without at …

Release 1.4.2

---

__init__.py
panels/fixtures.py

Rename the "Re-address only" checkbox to "Advanced edit" for clarity

Advanced edit

---

__init__.py
blender_utils.py
panels/setup.py

Add our own reload function, so we do not need to rely on other addons during development.

Add reload function

---

__init__.py
fixture.py
gdtf.py

- adjust timer for version checking on startup
- Fix gobo projections on fixtures without zoom.

Fix gobo without zoom

---

i18n/messages.pot
i18n/translations/ar_AA/LC_MESSAGES/messages.po
i18n/translations/cs_CZ/LC_MESSAGES/messages.po
i18n/translations/de_DE/LC_MESSAGES/messages.po
i18n/translations/en_US/LC_MESSAGES/messages.po
i18n/translations/fr_FR/LC_MESSAGES/messages.po
i18n/translations/it_IT/LC_MESSAGES/messages.po
i18n/translations/kk_KZ/LC_MESSAGES/messages.po
i18n/translations/nb_NO/LC_MESSAGES/messages.po
i18n/translations/pl_PL/LC_MESSAGES/messages.po
i18n/translations/pt_BR/LC_MESSAGES/messages.po
i18n/translations/sv_SE/LC_MESSAGES/messages.po
i18n/translations/tr_TR/LC_MESSAGES/messages.po
i18n/translations/zh_Hans/LC_MESSAGES/messages.po
i18n/update.sh

- remove file line numbers in yet another attempt to prevent weblate merge conflicts

Update translation strings, remove file line numbers

---

CHANGELOG.md
README.md
__init__.py
ifaddr/_win32.py

Release v1.5.1

---

__init__.py
dmx.py
dmx_temp_data.py
panels/dmx.py
panels/fixtures.py
panels/recorder.py
psn.py
pypsn/__init__.py
tracker.py
util.py

Adds configurable PSN trackers. Adds also a tracker object which can be a target for constrains for any Blender object. Adds a mapping screen to link fixtures to the tracker.

Add PosiStageNet (PSN) protocol

---

dmx.py
fixture.py
panels/fixtures.py
panels/programmer.py
util.py

Add support for more additive mixing colors: Amber, Lime, UV, White, WW, CW

---

dmx.py
panels/programmer.py

Makes working with larger scenes easier

Add icon/operator 'Center to selected' to the Programmer

---

CHANGELOG.md
README.md
__init__.py
gdtf.py
mvr.py

* Add icon 'Center to selected' to Programmer
* Add support for additive mixing: Amber, Lime, UV, White, WW, CW
* Update io_scene_3ds to LTS version and adjust GDTF and MVR to this LTS version
* Show error and a traceback on load3DS error
* Ensure fixtures can be removed even if their data is broken
* Add RGB versions of the provided source4 fixtures

Release v1.6.1

---

dmx.py
dmx_temp_data.py
panels/distribute.py

Add Fixture Align and Distribute panel

---

CHANGELOG.md
README.md
__init__.py

* Add Fixture Align and Distribute panel
* Reworking MVR import
* Add global option to Multiply BlenderDMX Spot Lights Intensity
* Add GDTF/MVR Import/Export to Blender menu
* Other small fixes, improvements and translations

Release 1.7.4

---

gdtf.py

- Improved creating constraints for conventional fixtures
- Removed grease pencil pixel factor wich will be removed from Blender 4.3 API

gdtf: Improved creating constraints and removed pixel factor

---

CHANGELOG.md
blender_manifest.toml

* MVR-xchange - initial websockets implementation
* Fix SVG import on some systems [Lily Hopkins]
* Translated using Weblate (Chinese (Simplified Han script))

Release v1.9.0

---

dmx.py
dmx_temp_data.py
logging.py
mvr.py
mvr_objects.py
mvrx_protocol.py
mvrxchange/mvr_xchange_blender.py
mvrxchange/mvrx_message.py
mvrxchange/mvrx_tcp_client.py
mvrxchange/mvrx_tcp_server.py
mvrxchange/mvrx_ws_client.py
panels/protocols/mvr.py
ruff.toml

Reworking the design of the modules, making sure we use correct socket connections where needed.

MVR-xchange: improvements to communication

---

color_utils.py
dmx.py

Map color picker to DMX RGB/CMY correctly and without drifting

Map color picker to DMX RGB/CMY correctly and without drifting

---

CHANGELOG.md
RELEASE.md
blender_manifest.toml
pyproject.toml

* Update translations
* Update MVR-xchange:
* Add periodic mDNS ticker
* Ensure that Blender DMX's mDNS reponds to queries
* Add the possibility to share any MVR file
* Add the possibility to save an MVR Commit as a file
* Increase speed of network transmission
* Show filename in the tooltip of commits lists

Release v2.0.6
